### ISSUE TITLE
Design & implement semantic cube

### ISSUE THREAD

**Issue by katiearriagam** [katiearriagam/Marbles#16]
Considerations:
* What operators do we work with?
* What are our data types? Are assets considered data types? I think yes.
* Possible design:
Create an enum for Data Types (DT) and Operators (OP)
matrix[DT][DT][OP] = DT;

**Comment by aa1148** [comment]
I didn't consider assets as data types, as we will not search for assets in the semantic cube. Rather we will search for an asset's position (integer), asset's size (integer), etc., which are our variable data types.

**Comment by aa1148** [comment]
Now I'm also starting to think about color. Is 'Color' a data type? Does we include it in the semantic cube? 🤔

**Comment by katiearriagam** [comment]
- Color should be included in the cube - the only valid scenario would be assignation between color - color.
- We should define the attributes for each asset in order to decide what else should be included in the **cube**.
